version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - '8080:80'
    links:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
