version: '3.1'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/Dockerfile
  #   # ports:
  #   #   - '8080:80'
  #   links:
  #     - php
  #   networks:
  #     - drink-up
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    networks:
      - drink-up
    ports:
      - '9000:9000'
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: psswrd
    restart: always
    ports:
      - '5432:5432'
    networks:
      - drink-up
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  drink-up:

volumes:
  db-data:
    driver: local
# version: '3'

# services:
#   web:
#     build:
#       context: .
#       dockerfile: docker/nginx/Dockerfile
#     ports:
#       - '8080:80'
#     volumes:
#       - .:/app/
#     links:
#       - php

#   php:
#     build:
#       context: .
#       dockerfile: docker/php/Dockerfile
#     volumes:
#       - .:/app/
